#region FirstRegion
all:
	@echo "Building project..."
#endregion

  # endregion Invalid end boundary
  # region Invalid start boundary

#region Second Region
clean:
	rm -rf build/
	#      region   InnerRegion  
	rm -rf logs/
	#endregion   ends  InnerRegion 
	rm -rf temp/
	#region  
	rm -rf cache/
	#   endregion  
#   endregion
